name: 'Terraform CI/CD'

on:
  push:
    branches: ['main']
  pull_request:

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/envs/int
    steps:
    - uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init -backend-config=backend.tfvars
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Plan
      run: terraform plan -var-file=terraform.tfvars
    - name: Zip Azure Function code
      run: |
       cd function_src
       pip install -r requirements.txt -t .python_packages/lib/site-packages
       zip -r ../function.zip .
       cd ..
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve -var-file=terraform.tfvars

